language: objective-c
osx_image: 10.14

jobs:
  include:
    - script: xcodebuild clean build test -project FruitApp.xcodeproj -scheme FruitApp -destination "platform=iOS Simulator,name=iPhone 8,OS=11.2" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=YES